include("entropies/LeonenkoProzantoSavani.jl")
include("entropies/GaoNaive.jl")
include("entropies/Goria.jl")
include("entropies/Lord.jl")
include("entropies/GenericKernel.jl")
include("entropies/Faivishevsky.jl")
include("entropies/Pal.jl")
