#testfile("divergence/divergence.jl")
testfile("entropy_conditional/entropy_conditional.jl")
testfile("mutualinfo/mutualinfo.jl")
testfile("conditional_mutualinfo/cmi.jl")
testfile("transferentropy.jl")
#testfile("predictive_asymmetry/predictive_asymmetry.jl")
