language: julia
os:
  - linux
  - windows
#  - osx

julia:
  - 1.3
  # - nightly # commented to save energy and time

before_script:
  - git config --global user.name "GitUser"
  - git config --global user.email "git@us.er"

matrix:
  allow_failures:
  - julia: nightly

notifications:
  email:
    on_success: never
    on_failure: always

env:
  matrix:
    - JULIA_SPECIALFUNCTIONS_BUILD_SOURCE=true
addons:
  apt_packages:
    - gfortran


jobs:
  include:
    - stage: "Documentation"
      julia: 1.3
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg;
                                    Pkg.develop(PackageSpec(path=pwd()));
                                    Pkg.instantiate();
                                    ENV["PYTHON"] = "";
                                    Pkg.build("PyCall");
                                    using Conda; Conda.add("scipy")'
        - julia --project=docs/ docs/make.jl
      after_success: skip
