language: julia
os:
  - linux
julia:
  - nightly
  - 1.0
matrix:
allow_failures:
- julia: nightly

script:
  - julia -e 'using Pkg; Pkg.build(); Pkg.add("PyCall")'
  - julia -e 'ENV["PYTHON"] = ""; using Pkg; Pkg.build("PyCall")'
  - julia -e 'using Conda; Conda.add("scipy")'
  - julia -e 'using Pkg; Pkg.test()'
