language: julia
os:
  - linux
  - windows
  # - osx

julia:
  - 1.3
  # - nightly

before_script:
  - git config --global user.name "GitUser"
  - git config --global user.email "git@us.er"

matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
  include:
    - stage: "Documentation"
      julia: 1.3
      os: linux
      script:
        - julia -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                    Pkg.instantiate();
                                    ENV["PYTHON"] = "";
                                    Pkg.build("PyCall");
                                    Pkg.add("Conda"); using Conda; Conda.add("scipy")'
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                    Pkg.instantiate();
                                    ENV["PYTHON"] = "";
                                    Pkg.build("PyCall");
                                    Pkg.add("Conda"); using Conda; Conda.add("scipy")'
        - julia --project=docs/ docs/make.jl
      after_success: skip
#after_success:
#  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'

notifications:
  email: false
