include("api.jl")

include("discrete/deprecate.jl")
include("discrete/AR1Unidir.jl")
include("discrete/AR1Bidir.jl")
include("discrete/Anishchenko.jl")
include("discrete/ChaoticMaps3.jl")
include("discrete/henon2.jl")
include("discrete/Henon3.jl")
include("discrete/Ikeda2.jl")
include("discrete/ChaoticNoisyLinear2.jl")
include("discrete/Nonlinear3.jl")
include("discrete/Peguin2.jl")
include("discrete/Logistic2Unidir.jl")
include("discrete/Logistic2Bidir.jl")
include("discrete/Logistic3CommonDriver.jl")
include("discrete/Logistic4Chain.jl")
include("discrete/UlamLattice.jl")
include("discrete/Var1.jl")
include("discrete/Verdes3.jl")

include("continuous/chuacircuits_driven.jl")
include("continuous/chuacircuit_nscroll_sine.jl")
include("continuous/hindmarsh_rose.jl")
include("continuous/mediated_link.jl")
include("continuous/lorenz_lorenz_bidir.jl")
include("continuous/lorenz_lorenz_lorenz_bidir_forced.jl")
include("continuous/lorenz_lorenz_lorenz_transitive.jl")
include("continuous/repressilator.jl")
include("continuous/rossler_rossler_bidir.jl")
include("continuous/rossler_rossler_rossler_bidir_forced.jl")
include("continuous/rossler_lorenz.jl")

include("noise.jl")
