include("LocalPermutationTest/local_permutation_test.jl")
include("SurrogateAssociationTest/SurrogateAssociationTest.jl")
include("JointDistanceDistributionTest.jl")
include("CorrTest.jl")
include("SECMITest.jl")