include("distances_and_divergences/distances_and_divergences.jl")
include("joint_entropies/joint_entropies.jl")
include("conditional_entropies/conditional_entropies.jl")
include("mutual_informations/mutual_informations.jl")
include("conditional_mutual_informations/conditional_mutual_informations.jl")