site_name:        CausalityTools.jl
repo_url:         https://github.com/kahaaga/CausalityTools.jl
site_description: Causality detection from time series in Julia.
site_author:      Kristian Agasøster Haaga

theme: material

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - mdx_math
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

docs_dir: 'build'

pages:
  - Home: index.md
  - Causality estimation:
    - Causality from time series: causalitytests/causality_from_time_series.md
    - Causality from uncertain data: 
      - Methods: causalitytests/causality_from_uncertain_data.md
      - Naive resampling: causalitytests/causality_from_uncertain_data_naive.md
      - Constrained resampling: causalitytests/causality_from_uncertain_data_naive_constrained.md
      - Binned resampling: causalitytests/causality_from_uncertain_data_binneddatacausalitytest.md
      - Interpolate-and-bin resampling: causalitytests/causality_from_uncertain_data_InterpolateBinTest.md
      - Random chunk resampling: causalitytests/causality_from_uncertain_data_RandomSequencesTest.md
      - Strictly increasing and interpolated resampling: causalitytests/causality_from_uncertain_data_strictlyincreasing_interpolated.md
    - Causality from dynamical systems: causalitytests/causality_from_dynamical_systems.md
  - Causality tests: 
    - Overview: causalitytests/causality_tests.md
    - JointDistanceDistributionTest: causalitytests/JointDistanceDistributionTest.md
    - CrossMappingTest: causalitytests/CrossMappingTest.md
    - ConvergentCrossMappingTest: causalitytests/ConvergentCrossMappingTest.md
    - SMeasureTest: causalitytests/SMeasureTest.md
    - TransferOperatorGridTest: causalitytests/TransferOperatorGridTest.md
    - VisitationFrequencyTest: causalitytests/VisitationFrequencyTest.md
    - ApproximateSimplexIntersectionTest: causalitytests/ApproximateSimplexIntersectionTest.md
    - ExactSimplexIntersectionTest: causalitytests/ExactSimplexIntersectionTest.md
    - Predictive asymmetry test: causalitytests/PredictiveAsymmetryTest.md
  - Fundamentals:
    - Discretization: causalitytoolsbase/discretization.md
    - Delay reconstruction: causalitytoolsbase/delay_reconstructions.md
    - Invariant properties over partitions:
      - Invariant measure: perronfrobenius/invariantmeasure.md
      - Transfer operator: perronfrobenius/transferoperator.md
  - Estimators and algorithms:
    - Transfer entropy:
      - Convenience functions: transferentropy/convenience_functions_te.md
      - Low-level estimators: transferentropy/transferentropy_estimators.md
      - Mapping delay reconstruction to marginals (TEVars): transferentropy/TEVars.md
      - Effect of discretization scheme: transferentropy/examples_TE_different_partitionings.md
    - CCM:
      - Overview: crossmappings/ccm/overview.md
      - Cross mapping: crossmappings/ccm/crossmapping.md
      - Converent cross mapping: crossmappings/ccm/convergentcrossmapping.md
    - Joint distance distribution: algorithms/joint_distance_distribution.md
    - Syntax overview: syntax_overview.md
  - Example systems: 
    - Overview: example_systems/example_systems_overview.md
    - Discrete systems: example_systems/example_systems_discrete.md
    - Continuous systems: example_systems/example_systems_continuous.md
    - Noise processes: example_systems/noise.md
  - Surrogate data:
    - Overview: surrogates/surrogates_overview.md
    - Methods:
      - IAAFT: surrogates/iaaft_docs.md
      - AAFT: surrogates/aaft_docs.md
      - Fourier surrogates, random phases: surrogates/randomphases_docs.md
      - Fourier surrogates, random amplitudes: surrogates/randomamplitudes_docs.md
      - Random shuffle: surrogates/randomshuffle_docs.md
  - Uncertain data handling:
    - BinnedDataCausalityTest: uncertaindata/BinnedDataCausalityTest.md
  - Tutorials/examples: 
    - List of tutorials: tutorials/list_of_tutorials.md
    - Causality from scalar data:
      - SMeasureTest: tutorials/tutorial_SMeasureTest.md
    - Causality from uncertain data:
      - PredictiveAsymmetryTest:
        - BinnedResampling: tutorials/causality/binned_uncertain_data/tutorial_BinnedDataCausalityTest_PredictiveAsymmetryTest_BinnedResampling.md
        - BinnedMeanResampling: tutorials/causality/binned_uncertain_data/tutorial_BinnedDataCausalityTest_PredictiveAsymmetryTest_BinnedMeanResampling.md
    - Worked examples:
      - Transfer entropy: worked_examples/worked_example_transferentropy.md
  - Changelog: CHANGELOG.md