site_name:        CausalityTools.jl
repo_url:         https://github.com/kahaaga/CausalityTools.jl
site_description: Causality detection from time series in Julia.
site_author:      Kristian Agasøster Haaga

theme: 
  name: material
  feature:
    tabs: true
  palette:
    primary: 'black' # check https://material.io/resources/color/ 
    accent: 'light blue' # https://www.materialpalette.com/
  font:
    text: 'Segoe UI'
    code: 'Source Code Pro'

# plugins:
#   - git-revision-date-localized:
#       type: datetime

extra:
  social:
    - type: 'github'
      link: 'https://github.com/kahaaga/CausalityTools.jl'

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - mdx_math
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

docs_dir: 'build'

pages:
  - Introduction and contents: index.md
  #- Overview:
  #- FAQ: FAQ.md
  #- Package overview: overview.md
  #- Syntax overview: syntax_overview.md
  - Estimating causality:
    - Overview: causalitytests/causality_tests_overview.md
    - From scalar time series: causalitytests/causality_tests.md
    - From uncertain time series: causalitytests/causality_from_uncertain_data_naive.md
    - From dynamical systems: causalitytests/causality_from_dynamical_systems.md
    - Causality tests:
      - Cross mappings:
        - CrossMappingTest: causalitytests/CrossMappingTest.md
        - ConvergentCrossMappingTest: causalitytests/ConvergentCrossMappingTest.md
      - Distance based:
        - JointDistanceDistributionTest: causalitytests/JointDistanceDistributionTest.md
        - SMeasureTest: causalitytests/SMeasureTest.md
      - Transfer entropy:
        - TransferOperatorGridTest: causalitytests/TransferOperatorGridTest.md
        - VisitationFrequencyTest: causalitytests/VisitationFrequencyTest.md
        - NearestNeighbourMITest: causalitytests/NearestNeighbourMITest.md
        - ApproximateSimplexIntersectionTest: causalitytests/ApproximateSimplexIntersectionTest.md
        - ExactSimplexIntersectionTest: causalitytests/ExactSimplexIntersectionTest.md
      - Predictive asymmetry:
        - PredictiveAsymmetryTest: causalitytests/PredictiveAsymmetryTest.md
        - NormalisedPredictiveAsymmetryTest: causalitytests/NormalisedPredictiveAsymmetryTest.md
      - Abstract test types: causalitytests/abstract_test_types.md
    - Meta-tests for uncertainty handling and subsampling:
        - Overview: causalitytests/causality_from_uncertain_data.md
        - BinnedDataCausalityTest: causalitytests/causality_from_uncertain_data_binneddatacausalitytest.md
        - ConstrainedTest: causalitytests/causality_from_uncertain_data_naive_constrained.md
        - InterpolateBinTest: causalitytests/causality_from_uncertain_data_InterpolateBinTest.md
        - RandomSequencesTest: causalitytests/causality_from_uncertain_data_RandomSequencesTest.md
        - Strictly increasing and interpolated resampling: causalitytests/causality_from_uncertain_data_strictlyincreasing_interpolated.md
  - Package ecosystem:
    - CausalityToolsBase:
      - Generalised delay reconstructions: causalitytoolsbase/delay_reconstructions.md
      - Discretization: causalitytoolsbase/discretization.md
    - Simplices: simplices/Simplices.md
    - PerronFrobenius:
        - Invariant measure: perronfrobenius/invariantmeasure.md
        - Transfer operator: perronfrobenius/transferoperator.md
    - Transfer entropy:
      - Overview: transferentropy/overview_te.md
      - Estimators: transferentropy/TE_estimators.md
      - Generalised delay embedding: transferentropy/generalised_delay_reconstructions.md
      - Assigning marginals: transferentropy/assigning_marginals.md
      - Methods: transferentropy/estimating_TE.md
      - Convenience methods: transferentropy/convenience_methods_te.md
      - Examples: 
        - Effect of discretization scheme: transferentropy/examples_TE_different_partitionings.md
    - Predictive asymmetry: PredictiveAsymmetry/predictive_asymmetry.md
    - CrossMappings:
      - Overview: crossmappings/ccm/overview.md
      - Cross mapping: crossmappings/ccm/crossmapping.md
      - Converent cross mapping: crossmappings/ccm/convergentcrossmapping.md
    - S-measure: SMeasure/s_measure.md
    - Joint distance distribution: JointDistanceDistribution/joint_distance_distribution.md
  - Surrogate data:
    - Overview: surrogates/surrogates_overview.md
    - IAAFT: surrogates/iaaft_docs.md
    - AAFT: surrogates/aaft_docs.md
    - Fourier surrogates, random phases: surrogates/randomphases_docs.md
    - Fourier surrogates, random amplitudes: surrogates/randomamplitudes_docs.md
    - Random shuffle: surrogates/randomshuffle_docs.md
  - SystemModels: 
    - Overview: SystemModels/SystemModels_overview.md
    - Continuous models: SystemModels/ContinuousModels.md
    - Parameter-randomisation: SystemModels/randomising.md
    - Internals: SystemModels/abstract_types.md
  - Example systems: 
    - Overview: example_systems/example_systems_overview.md
    - Discrete systems: example_systems/example_systems_discrete.md
    - Continuous systems: example_systems/example_systems_continuous.md
    - Noise processes: example_systems/noise.md
  - Tutorials/examples: 
    - List of tutorials: tutorials/list_of_tutorials.md
    - Causality from scalar time series:
      - SMeasureTest: tutorials/causality/tutorial_SMeasureTest.md
    - Causality from uncertain time series:
      - BinnedResampling + RandomSequencesTest: tutorials/causality/Tutorial_BinnedResampling_RandomSequencesTest_PredictiveAsymmetryTest_ar1_unidir.md
      - BinnedResampling: tutorials/causality/binned_uncertain_data/tutorial_BinnedDataCausalityTest_PredictiveAsymmetryTest_BinnedResampling.md
      - BinnedMeanResampling: tutorials/causality/binned_uncertain_data/tutorial_BinnedDataCausalityTest_PredictiveAsymmetryTest_BinnedMeanResampling.md
    - Worked examples:
      - Transfer entropy: worked_examples/worked_example_transferentropy.md
  - Changelog: CHANGELOG.md