site_name:        CausalityTools.jl docs (work in progress)
repo_url:         https://github.com/kahaaga/CausalityTools.jl
site_description: Causality detection from time series in Julia.
site_author:      Kristian Agasøster Haaga

theme: material

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - mdx_math
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

docs_dir: 'build'

pages:
  - Home: index.md
  - Glossary:
    - Delay embeddings (SSR): glossary/embed.md
    - Discretization schemes: glossary/discretization.md
    - Invariantizing: glossary/invariantizing/invariantizing.md

  - Dynamical invariants:
    - Transfer operator:
      - Overview: transferoperator/overview.md
      - Composite types:
        - Rectangular binning: transferoperator/composite_types/rectangular_binning.md
        - Triangulation, exact: transferoperator/composite_types/triang_exact.md
        - Triangulation, approximate: transferoperator/composite_types/triang_approx.md
      - Estimators:
        - Rectangular binning: transferoperator/transferoperator_rectangular_binning.md
        - Triangulation, exact: transferoperator/transferoperator_triang_exact.md
        - Triangulation, approximate: transferoperator/transferoperator_triang_approx.md
    - Invariant measures:
      - Overview: invariantmeasure/invariantmeasure_overview.md
      - Invariant measure: invariantmeasure/invariantmeasure.md
      - Rectangular estimators:
        - Rectangular: invariantmeasure/rectangularinvariantmeasure.md
        - Induced: invariantmeasure/inducedinvariantmeasure.md
        - Average: invariantmeasure/averageinvariantmeasure.md
  - Causal inference:

    - Transfer entropy:
      - Common interface: transferentropy/wrapper_TE.md
      - kNN estimator: transferentropy/estimator_TE_kNN.md
      - Transfer operator grid estimator: transferentropy/estimator_TE_transferoperator_grid.md
      - Visitation frequency estimator: transferentropy/estimator_TE_visitfreq.md

    - Cross mappings:
      - CCM:
        - Overview: crossmappings/ccm/overview.md
        - Cross map, single time series length: crossmappings/ccm/crossmapping.md
        - Cross map, multiple time series length: crossmappings/ccm/convergentcrossmapping.md
  - Surrogate data:
    - The method of surrogate data: surrogates/surrogates_overview.md
    - Methods:
      - Random shuffle: surrogates/randomshuffle_docs.md
      - Random amplitudes: surrogates/randomamplitudes_docs.md
      - Random phases: surrogates/randomphases_docs.md
      - AAFT: surrogates/aaft_docs.md
      - iAAFT: surrogates/iaaft_docs.md
    - Examples of surrogate realizations:
      - Random shuffle: surrogates/randomshuffle_example.md
      - Random amplitudes: surrogates/randomamplitudes_example.md
      - Random phases: surrogates/randomphases_example.md
      - AAFT: surrogates/aaft_example.md
      - iAAFT: surrogates/iaaft_example.md

  - Pre-implemented coupled dynamical systems:
    - ar1: example_systems/ar1.md
    - henon2: example_systems/henon2.md
    - logistic2: example_systems/logistic2.md
    - logistic3: example_systems/logistic3.md
    - linearmap3d_nonlinearcoupling: example_systems/linearmap3d_nonlinearcoupling.md
    - verdes: example_systems/verdes.md

  - Worked examples:
    - Transfer operator estimation:
      - Triangulation, exact: examples/transferoperators/exact.md
      - Triangulation, approximate: examples/transferoperators/approx.md

    - Convergent cross mapping:
      - Animation code: examples/crossmappings/ccm_gif.md
      - Example 1 - ar1: examples/crossmappings/examples_crossmappings_ar1.md
      - Example 2 - henon2: examples/crossmappings/examples_crossmappings_henon2.md
      - Example 3 - logistic2: examples/crossmappings/examples_crossmappings_logistic2.md
      - Example 4 - logistic3: examples/crossmappings/examples_crossmappings_logistic3.md
      - Example 5 - linearmap3d_nonlinearcoupling: examples/crossmappings/examples_crossmappings_linearmap3d_nonlinearcoupling.md
      - Example 6 - verdes: examples/crossmappings/examples_crossmappings_verdes.md
    - Interacting with DynamicalSystems.jl:
      - Example 1 - Information flow between coupled logistic maps: interop_dynamicalsystems_infoflow1.md
  - Plot recipes:
    - Recipe overview: plot_recipes/overview_recipes.md
    - Transfer operators:
      - Triangulation, exact: plot_recipes/recipe_transferoperator_triang_exact.md
      - Triangulation, approximate: plot_recipes/recipe_transferoperator_triang_approx.md
      - Rectangular binning: plot_recipes/recipe_transferoperator_rectangular_binning.md
