site_name:        CausalityTools.jl docs (work in progress)
repo_url:         https://github.com/kahaaga/CausalityTools.jl
site_description: Causality detection from time series in Julia.
site_author:      Kristian Agasøster Haaga

theme: material

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Home: index.md
  - Glossary:
    #- Delay embeddings: embed.md
    - Discretization schemes: discretization.md
    #  - Rectangular partitioning: partitioning_rectangular.md
    #  - Triangulation partitioning: partitioning_triangulation.md
  - Transfer operator:
    - Grid estimator: transferoperator/transferoperator_grid_docs.md
    #  - Triangulation estimator: transferoperator/transferoperator_triang_docs.md
    #- Examples:
    #  - Grid estimator: transferoperator/transferoperator_grid_example.md
    #  - Triangulation estimator: transferoperator/transferoperator_triang_example.md
  - Invariant measures: invariantmeasure/invariantmeasure_docs.md
    #- Examples: invariantmeasure/invariantmeasure_example.md
  - Transfer entropy (conditional mutual information):
    #- Common interface: transferentropy/commoninterface_TE.md
    #- Estimator documentation:
    - Common interface: transferentropy/wrapper_TE.md
    - kNN estimator: transferentropy/estimator_TE_kNN.md
    - Transfer operator grid estimator: transferentropy/estimator_TE_transferoperator_grid.md
    - Visitation frequency estimator: transferentropy/estimator_TE_visitfreq.md
  - Cross mappings: crossmappings/crossmapping.md
      #- Examples:
      #  - kNN: transferentropy/example_TE_kNN.md
      #  - Transfer operator grid: example_TE_transferoperator_grid.md
  #- Cross mapping causality:
  #  - Overview: cross_mappings.md
  - Surrogate data:
    - The method of surrogate data: surrogates/surrogates_overview.md
    - Methods:
      - Random shuffle: surrogates/randomshuffle_docs.md
      - Random amplitudes: surrogates/randomamplitudes_docs.md
      - Random phases: surrogates/randomphases_docs.md
      - AAFT: surrogates/aaft_docs.md
      - iAAFT: surrogates/iaaft_docs.md
    - Examples of surrogate realizations:
      - Random shuffle: surrogates/randomshuffle_example.md
      - Random amplitudes: surrogates/randomamplitudes_example.md
      - Random phases: surrogates/randomphases_example.md
      - AAFT: surrogates/aaft_example.md
      - iAAFT: surrogates/iaaft_example.md
  #- Recommended workflow: workflow.md
  - Example systems:
    - ar1: example_systems/ar1.md
    - henon2: example_systems/henon2.md
    - logistic2: example_systems/logistic2.md
    - logistic3: example_systems/logistic3.md
    - linearmap3d_nonlinearcoupling: example_systems/linearmap3d_nonlinearcoupling.md
    - verdes: example_systems/verdes.md
  - Worked examples:
    - Convergent cross mapping:
      - Animation code: examples/crossmappings/ccm_gif.md
      - Example, ar1: examples/crossmappings/examples_crossmappings_ar1.md
      - Example, henon2: examples/crossmappings/examples_crossmappings_henon2.md
      - Example, logistic2: examples/crossmappings/examples_crossmappings_logistic2.md
      - Example, logistic3: examples/crossmappings/examples_crossmappings_logistic3.md
      - Example, linearmap3d_nonlinearcoupling: examples/crossmappings/examples_crossmappings_linearmap3d_nonlinearcoupling.md
      - Example, verdes: examples/crossmappings/examples_crossmappings_verdes.md
    - Interacting with DynamicalSystems.jl:
      - Example 1 - Information flow between coupled logistic maps: interop_dynamicalsystems_infoflow1.md
  #- Examples:
  #  - TE partitioning schemes: transferentropy/examples_TE_different_partitionings.md
