
site_name:        CausalityTools.jl
repo_url:         https://github.com/kahaaga/CausalityTools.jl
site_description: A Julia package for detecting causality from time series.
site_author:      kahaaga

theme:
  name: 'material'

extra_css:
  - assets/documenter.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js
  - assets/documenter.js
  - assets/search.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'src'

pages:
  - Overview: index.md
  - Transfer (Perron-Frobenius) operator: transferoperator/transferoperator.md
  - Invariant measures/sets: invariantmeasure/invariantmeasure.md
  - Surrogate data:
    - What is a surrogate?: surrogates/surrogates.md
    - Random shuffle surrogates: surrogates/random_shuffle.md
    - Random phase Fourier surrogates: surrogates/Fourierphase.md
    - Random amplitude Fourier surrogates: surrogates/Fourieramp.md
    - AAFT: surrogates/aaft.md
    - IAAFT: surrogates/iaaft.md
  - Causality measures:
    - Overview: causalitytools.md
    - Transfer entropy:
      - Which estimator to choose?: transferentropy/overview.md
      - Transfer operator estimator: transferentropy/transferoperator.md
      - Visitation frequency estimator: transferentropy/visitfreq.md
      - Quick start examples: transferentropy/quickstart.md
  - Example systems:
      - Discrete maps: examplesystems/discrete_maps.md
      - Continuous: examplesystems/continuous.md
  - Tutorials: tutorials/tutorialoverview.md
