site_name:        CausalityTools.jl docs (work in progress)
repo_url:         https://github.com/kahaaga/CausalityTools.jl
site_description: Causality detection from time series in Julia.
site_author:      Kristian Agasøster Haaga

theme: material

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - mdx_math
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

docs_dir: 'build'

pages:
  - Home: index.md
  - Syntax overview: syntax_overview.md
  - CausalityToolsBase:
    - Discretization: causalitytoolsbase/discretization.md
  - PerronFrobenius:
    - Invariant measure: perronfrobenius/invariantmeasure.md
    - Transfer operator: perronfrobenius/transferoperator.md
  - TransferEntropy:
    - Estimators: transferentropy/transferentropy_estimators.md
    - Convenience functions: transferentropy/convenience_functions_te.md
  - Distance based measures:
    - CCM:
      - Overview: crossmappings/ccm/overview.md
      - Cross mapping: crossmappings/ccm/crossmapping.md
      - Converent cross mapping: crossmappings/ccm/convergentcrossmapping.md
    - Joint distance distribution: algorithms/joint_distance_distribution.md